server:
  port: 8088

aliyun:
  oss:
    project-name: bn
    access-id: DADFADFAFADEXSAD
    access-key: DADFADFAFADEXSAD
    bucket: tuku-test
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    expire: 0
